config/routes.rb
Rails.application.routes.draw do

  resources :session
  resources :users
  resources :people do
    collection do
      get 'search'
    end
  end
  resources :campaigns
  resources :donations

  root to: "session#index"

  resources :reports, only: [:index, :show] do
    collection do 
      get 'download'
    end
  end

end

app/models/person.rb
class Person < ApplicationRecord
  has_paper_trail

  has_many :donations

  scope :by_name, ->(){ order([:last_name, :first_name, :business_name])}

  validate :validate_some_name
  #validate :validate_address #some might want address, some might not

  def total_donations
    self.donations.inject(0){|t,d| t += d.amount}
  end

  def last_donation
    @last_donation ||= self.donations.order(:date).last
  end

  module CustomValidations
    def validate_some_name
      unless some_name_present
        self.errors.add(:base, "First, Last, or Business name must be present")
      end
    end

    def some_name_present
      first_name.present? || last_name.present? || business_name.present?
    end

    def validate_address
      unless all_address_fields
        self.errors.add(:base, "All basic address fields must be present")
      end
    end

    def all_address_fields
      address_1.present? && city.present? && state.present? && zip.present?
    end
  end
  include CustomValidations

  module Helpers
    def screen_name
      (self.first_name.to_s + ' ' +
         self.last_name.to_s + ' ' +
         self.business_name.to_s).
       strip
    end
  end
  include Helpers
end

app/models/person/search.rb
class Person::Search

  attr_accessor :term

  def self.with( term )
    s = Person::Search.new
    s.term = term
    s.search
  end

  def search
    Person.where("   ((first_name || ' ' || last_name) ILIKE :term) 
                  OR ((last_name || ' ' || first_name) ILIKE :term)
                  OR (business_name ILIKE :term)
                  OR first_name ILIKE :term
                  OR last_name ILIKE :term
                  OR business_name ILIKE :term",
                  term: "%#{term}%").
           order('last_name')
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def search
    people = Person::Search.with( params[:term] )
    if people.any?
      render json: people.map{|p| { value: p.id, label: p.screen_name } }
    else
      render json: { label: 'No matches' }
    end
  end

  def index
    @people = Person.by_name.paginate(page: params[:page], per_page: 25)
  end

  def new
    @person = Person.new
  end
  
  def create
    @person = Person.new( permitted_parameters ) 
    if @person.save
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def edit
    @person = Person.find( params[:id] )
  end
  
  def update
    @person = Person.find( params[:id] )
    if @person.update_attributes( permitted_parameters )
      redirect_to action: 'index'
    else
      render action: 'edit'
    end
  end

  def destroy
    @person = Person.find( params[:id] )
    if @person.donations.empty?
      @person.destroy
      flash[:notice] = 'Deleted'
    else
      flash[:notice] = 'Can\'t delete'
    end
    redirect_to action: 'index'
  end

  def show
    @person = Person.find( params[:id] )
  end
   

  private
  def permitted_parameters
    params.require(:person).
           permit(:first_name, :last_name, :business_name, :address_1,
                  :address_2, :city, :state, :zip, :email,
                  :phone_1, :phone_2, :solicitor,
                  :ok_to_email, :ok_to_mail, :ok_to_call) 
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form_fields.html.haml
.row
  .three.columns
    =f.label :first_name
    =f.text_field :first_name
  .three.columns
    =f.label :last_name
    =f.text_field :last_name
  .three.columns
    =f.label :busines_name
    =f.text_field :business_name
.row
  .three.columns
    =f.label :address_1
    =f.text_field :address_1
  .three.columns
    =f.label :address_2
    =f.text_field :address_2
  .three.columns
    =f.label :city
    =f.text_field :city
.row
  .three.columns
    =f.label :state
    =f.text_field :state
  .three.columns
    =f.label :zip
    =f.text_field :zip
  .three.columns
    =f.label :email
    =f.text_field :email
.row
  .three.columns
    =f.label :phone_1
    =f.text_field :phone_1
  .three.columns
    =f.label :phone_2
    =f.text_field :phone_2
  .three.columns
    =f.label :solicitor
    =f.text_field :solicitor

.row
  .three.columns
    =f.label :ok_to_email
    =f.check_box :ok_to_email
  .three.columns
    =f.label :ok_to_mail
    =f.check_box :ok_to_mail
  .three.columns
    =f.label :ok_to_call
    =f.check_box :ok_to_call

app/views/people/_row.html.haml
%tr
  %td
    -if person.first_name.present?
      =link_to person.first_name, edit_person_url(person)
  %td
    =person.last_name
  %td
    -if person.first_name.blank? && person.business_name.present?
      =link_to person.business_name, edit_person_url(person)
    -else
      =person.business_name
  %td
    =person.address_1
    =person.address_2
  %td
    =person.city
  %td
    =person.state
  %td
    =person.zip
  %td
    =person.email
  %td
    =person.phone_1
  %td
    =person.solicitor
  %td
    -if person.ok_to_email?
      EM
  %td
    -if person.ok_to_mail?
      SM
  %td
    -if person.ok_to_call?
      C
  %td
    =link_to number_to_currency(person.total_donations), donations_url(person_id: person.id), remote: true

app/views/people/_show.html.haml
%h5
  =link_to(@person.screen_name, edit_person_url(@person))

%div
  =@person.address_1
  =@person.address_2

%div
  =@person.city
  =@person.state
  =@person.zip


%div
  =@person.phone_1
  %br
  =@person.phone_2

%div

  -if @person.ok_to_email?
    Email ok,
  -if @person.ok_to_mail?
    Snail Mail ok,
  -if @person.ok_to_call?
    Calling ok,

-if @person.donations.empty?
  %div
    =link_to('Delete', person_url(@person), action: 'destroy', method: :delete, data: {confirm: 'Delete this entry?'}, class: 'button')

%h5
  Donations
  =number_to_currency(@person.total_donations)

%table.u-full-width
  %thead
    %th
      Campaign
    %th
      Donor
    %th
      Date
    %th
      Amount

  %tbody
    =render partial: 'donations/row', collection: @person.donations.order('date desc'), as: :donation
 

app/views/people/edit.html.haml
%h4
  Editing Donor
 
=error_messages_for @person

=form_for @person do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Update', class: 'button-primary'
     

-if @person.donations.empty?
  =link_to('Delete', person_url(@person), action: 'destroy', method: :delete, data: {confirm: 'Delete this entry?'}, class: 'button')

app/views/people/index.html.haml
%h5 
  Donors
  %span.smaller
    =link_to 'new', new_person_url

.row
  .three.columns
    =text_field_tag :menu_search, nil, placeholder: 'Search Donor'
  .nine.columns
    .pagination
      =will_paginate @people

#donor_page_content
  %table.u-full-width
    %thead
      %th
        First
      %th
        Last
      %th
        Company
      %th
        Address
      %th
        City
      %th
        State
      %th
        Zip
      %th
        Email
      %th
        Phone
      %th
        Contact
      %th
        Email
      %th
        Mail
      %th
        Call
      %th
        Donations

    %tbody
      =render partial: 'row', collection: @people, as: :person

:javascript

  $("#menu_search").autocomplete({
    source: "#{search_people_url}",
    select: function(event, ui){
      $.get({ url:   "people" + "/" + ui.item.value });
      return false;
    }
  });

app/views/people/new.html.haml
%h4
  New Donor
 
=error_messages_for @person

=form_for @person do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Create', class: 'button-primary'
     

app/views/people/show.js.erb
$("#donor_page_content").html("<%= j(render partial: 'show') %>");