config/routes.rb
Rails.application.routes.draw do

  resources :session
  resources :users
  resources :people do
    collection do
      get 'search'
    end
  end
  resources :campaigns
  resources :donations

  root to: "session#index"

  resources :reports, only: [:index, :show] do
    collection do 
      get 'download'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_paper_trail

  has_secure_password
  
  validates :login, presence: true, uniqueness: true

  validates :password, length: {minimum: 8, maximum: 72}, allow_blank: true 

  scope :active, ->(){ where(active: true) }
  scope :by_name, ->(){ order(:login) }

  validate :at_least_one_admin

  module Validations
    def at_least_one_admin
      unless one_admin_remains
        self.errors.add(:base, "The system needs at least one active user")
      end
    end

    def one_admin_remains
      User.active.where('id != ?', self.id.to_i).any?
    end
  end
  include Validations

end

app/models/user/authenticate.rb
class User::Authenticate

  attr_accessor :params

  def self.with( params )
    a = User::Authenticate.new
    a.params = params
    a.authenticate
  end

  def authenticate
    if authenticated
      return user
    end
  end

  def authenticated
    user && password_match
  end

  def user
    @user ||= get_user
  end

  def get_user
    User.active.where(["login = ?", login]).first
  end

  def password_match
    user.authenticate password
  end

  def login
    params[:login]
  end

  def password
    params[:password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.by_name
  end

  def new
    @user = User.new(active: true)
  end
  
  def create
    @user = User.new( permitted_params )
    if @user.save
      flash[:success] = 'Created'
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes( permitted_update )
      flash[:success] = 'Updated'
      redirect_to users_url
    else
      render action: 'edit'
    end
  end

  private
  def permitted_params
    params.require(:user).permit(:login, :password, :password_confirmation, :active)
  end

  def permitted_update
    params.require(:user).permit(:password, :password_confirmation, :active)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_fields.html.haml
.row
  .three_columns
    =f.label :login
    =f.text_field :login
  .three_columns
    =f.label :active
    =f.check_box :active
.row
  .tree_columns
    =f.label :password
    =f.password_field :password
.row
  .tree_columns
    =f.label :password_confirmation
    =f.password_field :password_confirmation

app/views/users/_row.html.haml
%tr
  %td
    =link_to(user.login, edit_user_url(user))
  %td
    -if user.active?
      Yes
    -else
      No

app/views/users/edit.html.haml
%h4
  Editing User
 
=error_messages_for @user

=form_for @user do |f|

  .row
    .three_columns
      %label 
        Login
      %div
        =@user.login
    .three_columns
      =f.label :active
      =f.check_box :active
  .row
    .tree_columns
      =f.label :password
      =f.password_field :password
  .row
    .tree_columns
      =f.label :password_confirmation
      =f.password_field :password_confirmation


  .row
    .three.columns
      =f.submit 'Update User', class: 'button-primary'
     

app/views/users/index.html.haml
%h5
  Users
  %span.smaller
    =link_to 'new', new_user_url


%table.u-full-width
  %thead
    %th
      Login
    %th
      Active
  %tbody
    =render partial: 'row', collection: @users, as: :user
 

app/views/users/new.html.haml
%h4
  New User
 
=error_messages_for @user

=form_for @user do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Create User', class: 'button-primary'
     