config/routes.rb
Rails.application.routes.draw do

  resources :session
  resources :users
  resources :people do
    collection do
      get 'search'
    end
  end
  resources :campaigns
  resources :donations

  root to: "session#index"

  resources :reports, only: [:index, :show] do
    collection do 
      get 'download'
    end
  end

end

app/models/donation.rb
class Donation < ApplicationRecord
  has_paper_trail

  belongs_to :person
  belongs_to :campaign

  validates :person_id, presence: true, numericality: true
  validates :campaign_id, presence: true, numericality: true
  validates :amount_cents, presence: true
  validates :date, presence: true

  monetize :amount_cents

end

app/models/report/donation.rb
class Report::Donation

  def self.data
    Report::Donation.new.data
  end

  def data
    @data = CSV.generate_line( self.csv_header )
    report_array.each do |report_line|
      @data << CSV.generate_line( report_line ) 
    end
    @data
  end

  def csv_header
    [ 
      'id',   'Campaign', 'Donor', 
      'Date', 'Solicitor', 'Amount'
    ]
  end

  def report_array
    l = []
    ::Donation.find_each do |donation|
      l << line_for(donation)
    end
    l
  end

  def line_for(donation)
    [
      donation.id,
      donation.campaign.label,
      donation.person.screen_name,
      donation.date.try(:strftime, '%Y-%m-%d'),
      donation.person.solicitor,
      donation.amount.to_s
    ]
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def index
    if params[:person_id].present?
      @person    = Person.find( params[:person_id] )
      @donations = @person.donations.order('date desc')
    elsif params[:campaign_id].present?
      @campaign  = Campaign.find( params[:campaign_id] )
      @donations = @campaign.donations.order('date desc')
    else
      @donations = Donation.order('id desc').paginate(per_page: 30, page: params[:page])
    end
  end

  def new
    @donation = Donation.new( campaign_default )
    @campaigns = Campaign.order("id desc")
  end

  def create
    @donation = Donation.new( permitted_params )
    if @donation.save
      flash[:success] = 'Created'
      redirect_to donations_url
    else
      @campaigns = Campaign.order("id desc")
      render action: 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
    @campaigns = Campaign.order("id desc")
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update_attributes( permitted_params )
      flash[:success] = 'Updated'
      redirect_to donations_url
    else
      @campaigns = Campaign.order("id desc")
      render action: 'edit'
    end
  end

  private
  def permitted_params
    params.require(:donation).permit(:person_id, :campaign_id, :amount, :date)
  end

  def campaign_default
    {
      campaign: Donation.last.try(:campaign),
      date:     Donation.last.try(:date)
    }
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form_fields.html.haml
.row
  .three.columns
    =f.label :campaign
    =f.select :campaign_id, options_from_collection_for_select( @campaigns, :id, :label )
  .five.columns
    =f.label 'Donor', for: :person
    =f.hidden_field :person_id
    =text_field_tag :search_person_field, @donation.person.try(:screen_name)
.row
  .three.columns
    =f.label :date
    =f.date_field :date
  .three.columns
    =f.label :amount
    =f.text_field :amount

app/views/donations/_javascript.html.haml
:javascript

  $("#search_person_field").autocomplete({
    source: '#{search_people_url}',
    select: function(event, ui){
      $(this).val(ui.item.label);
      $("#donation_person_id").val( ui.item.value );
      return false;
    }
  });

app/views/donations/_person_donations.html.haml
%h5
  -if @person.present?
    =@person.screen_name
  -elsif @campaign.present?
    =@campaign.label
    ="(#{@donations.count})"
  Donations

%table.u-full-width
  %thead
    %th
      Campaign
    %th
      Donor
    %th
      Date
    %th
      Amount

  %tbody
    =render partial: 'row', collection: @donations, as: :donation
 

app/views/donations/_row.html.haml
%tr
  %td
    =donation.campaign.label
  %td
    =donation.person.screen_name
  %td
    =donation.date.strftime('%D')
  %td
    =link_to(number_to_currency( donation.amount ), edit_donation_url( donation ))

app/views/donations/edit.html.haml
%h4
  Editing Donation
 
=error_messages_for @donation

=form_for @donation do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Update Donation', class: 'button-primary'
     

=render partial: 'javascript'

app/views/donations/index.html.haml
%h5
  Donations
  %span.smaller
    =link_to 'new', new_donation_url

.pagination
  =will_paginate @donations


%table.u-full-width
  %thead
    %th
      Campaign
    %th
      Donor
    %th
      Date
    %th
      Amount

  %tbody
    =render partial: 'row', collection: @donations, as: :donation
 

app/views/donations/index.js.erb
$('#modal').show();
$('#modal_content').html("<%= j(render partial: 'person_donations') %>");

app/views/donations/new.html.haml
%h4
  New Donation
 
=error_messages_for @donation

=form_for @donation do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Enter Donation', class: 'button-primary'
     

=render partial: 'javascript'