config/routes.rb
Rails.application.routes.draw do

  resources :session
  resources :users
  resources :people do
    collection do
      get 'search'
    end
  end
  resources :campaigns
  resources :donations

  root to: "session#index"

  resources :reports, only: [:index, :show] do
    collection do 
      get 'download'
    end
  end

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_paper_trail

  has_many :donations

  validates :label, presence: true, uniqueness: true
  validates :date, presence: true

  def total_donations
    self.donations.inject(0){|t,d| t += d.amount }
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.order('date desc').paginate(page: params[:page], per_page: 30)
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new( permitted_params )
    if @campaign.save
      flash[:success] = 'Created'
      redirect_to campaigns_url
    else
      render action: 'new'
    end
  end

  def edit
    @campaign = Campaign.find( params[:id] )
  end

  def update
    @campaign = Campaign.find( params[:id] )
    if @campaign.update_attributes( permitted_params )
      flash[:success] = 'Updated'
      redirect_to campaigns_url
    else
      render action: 'edit'
    end
  end

  private
  def permitted_params
    params.require(:campaign).permit(:label, :date, :note)
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form_fields.html.haml
.row
  .three.columns
    =f.label :label
    =f.text_field :label
  .three.columns
    =f.label :date
    =f.date_field :date
.row
  .six.columns
    =f.label :note
    =f.text_area :note, size: '40x3'

app/views/campaigns/_row.html.haml
%tr
  %td
    =link_to campaign.label, edit_campaign_url(campaign)
  %td
    -if campaign.date.present?
      =campaign.date.strftime('%D')
  %td
    =campaign.note.to_s[0,35] 
  %td
    =link_to number_to_currency(campaign.total_donations), donations_url(campaign_id: campaign.id), remote: true

app/views/campaigns/edit.html.haml
%h4
  Editing Campaign
 
=error_messages_for @campaign

=form_for @campaign do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Update', class: 'button-primary'
     

app/views/campaigns/index.html.haml
%h5
  Campaigns
  %span.smaller
    =link_to 'new', new_campaign_url


.pagination
  =will_paginate @campaigns

%table.u-full-width
  %thead
    %th
      Label
    %th
      Date
    %th
      Note
    %th
      Donations
  %tbody
    =render partial: 'row', collection: @campaigns, as: :campaign
 

app/views/campaigns/new.html.haml
%h4
  New Campaign
 
=error_messages_for @campaign

=form_for @campaign do |f|

  =render partial: 'form_fields', locals: {f: f}

  .row
    .three.columns
      =f.submit 'Create', class: 'button-primary'
     